/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ro.utcluj.ssatr.simulator.lift;

import javax.swing.JButton;

/**
 *
 * @author mihai.hulea
 */
public class PanouLiftJFrame extends javax.swing.JFrame {

    //private Lift lift = new Lift();
    private Lift lift;
    
    /**
     * Creates new form PanouLiftJFrame
     */
    public PanouLiftJFrame() {
        initComponents();
        lift = new Lift(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bN5 = new javax.swing.JButton();
        bN4 = new javax.swing.JButton();
        bN2 = new javax.swing.JButton();
        bN1 = new javax.swing.JButton();
        bN0 = new javax.swing.JButton();
        txtComanda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bN5.setText("4");
        bN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN5ActionPerformed(evt);
            }
        });

        bN4.setText("3");
        bN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN4ActionPerformed(evt);
            }
        });

        bN2.setText("2");
        bN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN2ActionPerformed(evt);
            }
        });

        bN1.setText("1");
        bN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN1ActionPerformed(evt);
            }
        });

        bN0.setText("0");
        bN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bN5)
                    .addComponent(bN4)
                    .addComponent(bN2)
                    .addComponent(bN1)
                    .addComponent(bN0))
                .addContainerGap(82, Short.MAX_VALUE))
            .addComponent(txtComanda)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bN5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bN4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bN2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bN0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN0ActionPerformed
        //String txt = bN0.getText();
        String txt = ((JButton)evt.getSource()).getText();
        lift.executaComanda(txt);
    }//GEN-LAST:event_bN0ActionPerformed

    private void bN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN1ActionPerformed
        // TODO add your handling code here:
        String txt = ((JButton)evt.getSource()).getText();
        lift.executaComanda(txt);
    }//GEN-LAST:event_bN1ActionPerformed

    private void bN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN2ActionPerformed
        // TODO add your handling code here:
        String txt = ((JButton)evt.getSource()).getText();
        lift.executaComanda(txt);
    }//GEN-LAST:event_bN2ActionPerformed

    private void bN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN4ActionPerformed
        // TODO add your handling code here:
        String txt = ((JButton)evt.getSource()).getText();
        lift.executaComanda(txt);
    }//GEN-LAST:event_bN4ActionPerformed

    private void bN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN5ActionPerformed
        // TODO add your handling code here:
        String txt = ((JButton)evt.getSource()).getText();
        lift.executaComanda(txt);
    }//GEN-LAST:event_bN5ActionPerformed

    public void setText(String msg){
        txtComanda.setText(msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanouLiftJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanouLiftJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanouLiftJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanouLiftJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanouLiftJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bN0;
    private javax.swing.JButton bN1;
    private javax.swing.JButton bN2;
    private javax.swing.JButton bN4;
    private javax.swing.JButton bN5;
    private javax.swing.JTextField txtComanda;
    // End of variables declaration//GEN-END:variables
}
